# Generated by Django 5.0.6 on 2024-06-14 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=100)),
                ('tipo_especializacion', models.CharField(max_length=100)),
                ('año_de_ingreso', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_del_curso', models.CharField(max_length=100)),
                ('duracion', models.CharField(max_length=20)),
                ('profesor_a_cargo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Especializacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_de_especializacion', models.CharField(max_length=100)),
                ('duracion', models.CharField(max_length=20)),
                ('campo_de_estudio', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=100)),
                ('materia_que_dicta', models.CharField(max_length=100)),
                ('años_de_experiencia', models.CharField(max_length=20)),
            ],
        ),
    ]
